### ISSUE TITLE
unable to load pathom.pedestal/index-html 

### ISSUE THREAD

**Issue by alidcast** [jlesquembre/pathom-pedestal#1]
The `index-html` function is causing an execution error: 
```
Execution error (IllegalArgumentException) at pathom.pedestal/index-html (pedestal.clj:29).
Cannot open <nil> as a Reader.
```

Maybe the resource `"pathom-viz/index.html"`  has moved?

**Comment by jlesquembre** [comment]
Thanks for reporting this.

Are you running the project with `clj -A:dev` ? In that case, did you clone the submodule and run `make compile-viz`? I notice that I forgot to mention the submodule in the readme, I just added a note about it.

If you are still having the error, could you provide an example to reproduce it? Thanks!

**Comment by alidcast** [comment]
No I did not clone repo, I'm using `pathom.pedestal` in my own project as a dependency.

i.e.
```
(def routes
  (route/expand-routes (pathom-routes {:pathom-viz? true :parser parser})))
```

Are there extra steps required for this to work?

**Comment by jlesquembre** [comment]
No extra steps required, with 0.1.5-SNAPSHOT works. 
I see that with 0.1.5 the assets were not included in the jar, it looks like I did something wrong on that release. I'm going to fix it and make a new release

**Comment by jlesquembre** [comment]
Thanks for your patience. `0.1.7` should fix that issue. There are no code changes, I didn't properly generate the jar file. To avoid making the same mistake again, I automated the release process.
